### ISSUE TITLE
cds-holder-java throws ' no such file or directory ' error on start

### ISSUE THREAD

**Issue by rickos-aws** [ConsumerDataStandardsAustralia/cds-holder-java-spring#3]
**Description**
The consumerdatastandardsaustralia/cds-holder-java image does not appear to start and throws the following error when running the following command:
`docker run -p 8080:8080 consumerdatastandardsaustralia/cds-holder-java:0.0.4-SNAPSHOT`

**Error Message**
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/usr/bin/java\": stat /usr/bin/java: no such file or directory": unknown.

Ive tried this image on both MacOS and Ubuntu and both display the same behaviour. 
The previous copy of 0.0.2-SNAPSHOT seems to start fine however. 

Cheers

**Comment by csirostu** [comment]
@rickos-aws The Dockerfile shipped with an entry point of ``/usr/bin/java``, the correct entry point is ``/usr/local/openjdk-8/bin/java``.

These changes are committed in the new branch ``sprint-6``: https://github.com/ConsumerDataStandardsAustralia/cds-holder-java-spring/commit/420656f5cd0dbcddbe4a3fcc7719cd4bd9acf917

I'm reticent to do a new publish just yet as likely further changes but for those finding this issue, interim run command below:
``docker run -p 8080:8080 --entrypoint="/usr/local/openjdk-8/bin/java" consumerdatastandardsaustralia/cds-holder-java:0.0.4-SNAPSHOT  -jar /opt/cds-holder/holder.jar ``

Thanks,

Stuart
